#include <stdio.h>
#include <stdlib.h>
#include "pqueue.h"

// generated by getconsts.py
#define ALPHABET_SIZE 71
const char alphabet[ALPHABET_SIZE] = "30Z[]_XJV()*PUFzKGQBL\"YNqjRxCOED;M?S:WH!TA-Iv.kbpmfyc,wg'u\nldrsinhoate ";
const int freq[ALPHABET_SIZE] = { 1, 1, 1, 2, 2, 4, 4, 8, 42, 56, 56, 60, 65, 66, 74, 77, 82, 83, 84, 91, 98, 113, 114, 120, 125, 138, 140, 144, 145, 176, 188, 192, 194, 200, 202, 218, 233, 237, 284, 450, 472, 638, 669, 733, 804, 978, 1076, 1384, 1459, 1907, 1927, 2148, 2254, 2418, 2438, 2448, 2871, 3402, 3597, 4618, 4739, 5298, 6282, 6781, 6896, 7090, 7970, 8153, 10216, 13387, 28917, };

typedef struct EncodingInfo {
    int code;
    int length;
} EncodingInfo;

char* read_file(char* path, int* length_ref);
void symbol_to_code_recursive(TreeNode* node, EncodingInfo* code[], int so_far, int length);

int main() {
    printf("Compressing aliceinwonderland.txt...\n");

    printf("Frequencies:\n");
    for (int i = 0; i < ALPHABET_SIZE; i++) {
        printf("%c: %d\n", alphabet[i], freq[i]);
    }

    Node* pq = NULL;

    // Create a leaf node for each symbol and add it to the priority queue.
    for (int i = 0; i < ALPHABET_SIZE; i++) {
        sortedAppend(&pq, make_pq_node(alphabet[i], freq[i]));
    }

    // * The below algorithm is from https://en.wikipedia.org/wiki/Huffman_coding#Informal_description
    // while there is more than one node in the queue:
    while (pq->next != NULL) {
        // remove the two nodes of lowest weight from the queue
        Node* first = pq;
        pq = pq->next;
        Node* second = pq;
        pq = pq->next;

        // create a new internal node with these two nodes as children and with weight equal to the sum of the two nodes' probabilities.
        Node* internal = make_pq_node('\0', first->weight + second->weight);
        internal->node->left = first->node;
        internal->node->right = second->node;

        // add the new node to the queue.
        sortedAppend(&pq, internal);
    }

    // the remaining node is the root node and the tree is complete.
    TreeNode* tree = pq->node;

    // traverse the tree to generate mapping from symbol to binary code
    EncodingInfo* code[255] = { 0 };
    symbol_to_code_recursive(tree, code, 0, 0);

    // print out code table
    printf("\n\nCode table:\n");
    for (int c = 0; c < 255; c++) {
        if (code[c] != NULL) {
            printf("%c: %d\t(%d bits)\n", c, code[c]->code, code[c]->length);
        }
    }

    // encode
    int length;
    char* file = read_file("aliceinwonderland.txt", &length);
    char* encode_buf = malloc(length);

    int total_bit_length = 0;
    for (int i = 0; i < length; i++) {
        EncodingInfo* info = code[file[i]];
        if (info == NULL) {
            printf("Error: no encoding for character %c\n", file[i]);
            return 1;
        }
        // TODO
        total_bit_length += info->length;
    }

}

void symbol_to_code_recursive(TreeNode* node, EncodingInfo* code[], int so_far, int length) {
    if (node->left == NULL && node->right == NULL) {
        // is a leaf node
        EncodingInfo* info = malloc(sizeof(EncodingInfo));
        info->code = so_far;
        info->length = length;
        code[node->data] = info;
    } else {
        // is an internal node
        so_far <<= 1;
        if (node->left != NULL) symbol_to_code_recursive(node->left, code, so_far | 0, length + 1);
        if (node->right != NULL) symbol_to_code_recursive(node->right, code, so_far | 1, length + 1);
    }
}

char* read_file(char* path, int* length_ref) {
    FILE* f = fopen(path, "r");
    char* buffer;

    fseek(f, 0, SEEK_END);
    length_ref = ftell(f);
    fseek(f, 0, SEEK_SET);
    buffer = malloc(length_ref);
    if (buffer)
    {
        fread(buffer, 1, length_ref, f);
    }
    fclose(f);

    return buffer;
}